//Mold Fitness :: MiU Project 1 :: By Tony Keiser 1212
var json = {
	
	"activity1":{
		"name": 	["Name:","Jake Lea"],
		"pass":	    ["Password:", "abc"],
		"gender": 	["Gender:", "Male"],
		"weight": 	["Weight:", "150"],
		"muscle": 	["Activity:", "Rest"],
		"sets": 	["Number of Sets:", "0"],
		"reps":		["Number of Reps:", "0"],
		"cardio":	["Cardio Today:", false],
		"time":		["Cardio Time:", "0 Minutes"],
		"notes":	["Notes:", "Sleep tight..."],
		"date":		["Date:", "2013-05-03"]
	},
	"activity2":{
		"name": 	["Name:","Bo Brown"],
		"pass":	    ["Password:", "123"],
		"gender": 	["Gender:", "Male"],
		"weight": 	["Weight:", "230"],
		"muscle": 	["Activity:", "Chest"],
		"sets": 	["Number of Sets:", "5"],
		"reps":		["Number of Reps:", "10"],
		"cardio":	["Cardio Today:", true],
		"time":		["Cardio Time:", "10 Minutes"],
		"notes":	["Notes:", "Go HARD or go HOME!"],
		"date":		["Date:", "2013-05-02"]
	},
	"activity3":{
		"name": 	["Name:","Pagi Ando"],
		"pass":	    ["Password:", "zxy"],
		"gender": 	["Gender:", "Female"],
		"weight": 	["Weight:", "105"],
		"muscle": 	["Activity:", "Legs"],
		"sets": 	["Number of Sets:", "3"],
		"reps":		["Number of Reps:", "10"],
		"cardio":	["Cardio Today:", true],
		"time":		["Cardio Time:", "30 Minutes"],
		"notes":	["Notes:", "Summer TIME!"],
		"date":		["Date:", "2013-05-04"]
	},
	"activity4":{
		"name": 	["Name:","Mike Jones"],
		"pass":	    ["Password:", "123"],
		"gender": 	["Gender:", "Male"],
		"weight": 	["Weight:", "180"],
		"muscle": 	["Activity:", "Back"],
		"sets": 	["Number of Sets:", "5"],
		"reps":		["Number of Reps:", "10"],
		"cardio":	["Cardio Today:", false],
		"time":		["Cardio Time:", "0 Minutes"],
		"notes":	["Notes:", ""],
		"date":		["Date:", "2013-05-10"]
	},
	"activity5":{
		"name": 	["Name:","Tony Keiser"],
		"pass":	    ["Password:", "123"],
		"gender": 	["Gender:", "Male"],
		"weight": 	["Weight:", "170"],
		"muscle": 	["Activity:", "Abs"],
		"sets": 	["Number of Sets:", "5"],
		"reps":		["Number of Reps:", "20"],
		"cardio":	["Cardio Today:", true],
		"time":		["Cardio Time:", "30 Minutes"],
		"notes":	["Notes:", ""],
		"date":		["Date:", "2013-05-12"]
	},
	"activity6":{
		"name": 	["Name:","Mike Golob"],
		"pass":	    ["Password:", "123"],
		"gender": 	["Gender:", "Male"],
		"weight": 	["Weight:", "150"],
		"muscle": 	["Activity:", "Cardio"],
		"sets": 	["Number of Sets:", "0"],
		"reps":		["Number of Reps:", "0"],
		"cardio":	["Cardio Today:", true],
		"time":		["Cardio Time:", "60 Minutes"],
		"notes":	["Notes:", ""],
		"date":		["Date:", "2013-05-12"]
	},
	"activity7":{
		"name": 	["Name:","Kody Dyson-Sem"],
		"pass":	    ["Password:", "123"],
		"gender": 	["Gender:", "Male"],
		"weight": 	["Weight:", "280"],
		"muscle": 	["Activity:", "Legs"],
		"sets": 	["Number of Sets:", "3"],
		"reps":		["Number of Reps:", "10"],
		"cardio":	["Cardio Today:", false],
		"time":		["Cardio Time:", "0 Minutes"],
		"notes":	["Notes:", ""],
		"date":		["Date:", "2013-05-20"]
	},	
	"activity8":{
		"name": 	["Name:","Brittany Ann"],
		"pass":	    ["Password:", "abc"],
		"gender": 	["Gender:", "Female"],
		"weight": 	["Weight:", "120"],
		"muscle": 	["Activity:", "Rest"],
		"sets": 	["Number of Sets:", "0"],
		"reps":		["Number of Reps:", "0"],
		"cardio":	["Cardio Today:", false],
		"time":		["Cardio Time:", "0 Minutes"],
		"notes":	["Notes:", ""],
		"date":		["Date:", "2013-05-21"]
	},		
	"activity9":{
		"name": 	["Name:","Karen Peterson"],
		"pass":	    ["Password:", "123"],
		"gender": 	["Gender:", "Female"],
		"weight": 	["Weight:", "111"],
		"muscle": 	["Activity:", "Cardio"],
		"sets": 	["Number of Sets:", "0"],
		"reps":		["Number of Reps:", "0"],
		"cardio":	["Cardio Today:", true],
		"time":		["Cardio Time:", "30 Minutes"],
		"notes":	["Notes:", ""],
		"date":		["Date:", "2013-05-13"]
	},	
	"activity10":{
		"name": 	["Name:","Randi Keiser"],
		"pass":	    ["Password:", "123"],
		"gender": 	["Gender:", "Female"],
		"weight": 	["Weight:", "140"],
		"muscle": 	["Activity:", "Abs"],
		"sets": 	["Number of Sets:", "3"],
		"reps":		["Number of Reps:", "30"],
		"cardio":	["Cardio Today:", false],
		"time":		["Cardio Time:", "0 Minutes"],
		"notes":	["Notes:", ""],
		"date":		["Date:", "2013-05-24"]
	},	
	"activity11":{
		"name": 	["Name:","Micheal Brain"],
		"pass":	    ["Password:", "123"],
		"gender": 	["Gender:", "Male"],
		"weight": 	["Weight:", "220"],
		"muscle": 	["Activity:", "Arms"],
		"sets": 	["Number of Sets:", "3"],
		"reps":		["Number of Reps:", "10"],
		"cardio":	["Cardio Today:", false],
		"time":		["Cardio Time:", "0 Minutes"],
		"notes":	["Notes:", ""],
		"date":		["Date:", "2013-05-30"]
	},
	"activity12":{
		"name": 	["Name:","Kevin Larson"],
		"pass":	    ["Password:", "123"],
		"gender": 	["Gender:", "Male"],
		"weight": 	["Weight:", "240"],
		"muscle": 	["Activity:", "Chest"],
		"sets": 	["Number of Sets:", "3"],
		"reps":		["Number of Reps:", "10"],
		"cardio":	["Cardio Today:", false],
		"time":		["Cardio Time:", "0 Minutes"],
		"notes":	["Notes:", ""],
		"date":		["Date:", "2013-05-18"]
	},		
	"activity13":{
		"name": 	["Name:","Dani Randle"],
		"pass":	    ["Password:", "123"],
		"gender": 	["Gender:", "Female"],
		"weight": 	["Weight:", "160"],
		"muscle": 	["Activity:", "Cardio"],
		"sets": 	["Number of Sets:", "0"],
		"reps":		["Number of Reps:", "0"],
		"cardio":	["Cardio Today:", true],
		"time":		["Cardio Time:", "45 Minutes"],
		"notes":	["Notes:", ""],
		"date":		["Date:", "2013-05-20"]
	},
	"activity14":{
		"name": 	["Name:","Brandon Keiser"],
		"pass":	    ["Password:", "123"],
		"gender": 	["Gender:", "Male"],
		"weight": 	["Weight:", "210"],
		"muscle": 	["Activity:", "Arms"],
		"sets": 	["Number of Sets:", "3"],
		"reps":		["Number of Reps:", "15"],
		"cardio":	["Cardio Today:", true],
		"time":		["Cardio Time:", "10 Minutes"],
		"notes":	["Notes:", ""],
		"date":		["Date:", "2013-05-17"]
	},	
	"activity15":{
		"name": 	["Name:","Max Keiser"],
		"pass":	    ["Password:", "123"],
		"gender": 	["Gender:", "Male"],
		"weight": 	["Weight:", "180"],
		"muscle": 	["Activity:", "Chest"],
		"sets": 	["Number of Sets:", "5"],
		"reps":		["Number of Reps:", "10"],
		"cardio":	["Cardio Today:", true],
		"time":		["Cardio Time:", "10 Minutes"],
		"notes":	["Notes:", ""],
		"date":		["Date:", "2013-05-17"]
	},	
	"activity16":{
		"name": 	["Name:","Jake Lea"],
		"pass":	    ["Password:", "123"],
		"gender": 	["Gender:", "Male"],
		"weight": 	["Weight:", "140"],
		"muscle": 	["Activity:", "Legs"],
		"sets": 	["Number of Sets:", "3"],
		"reps":		["Number of Reps:", "10"],
		"cardio":	["Cardio Today:", false],
		"time":		["Cardio Time:", "0 Minutes"],
		"notes":	["Notes:", ""],
		"date":		["Date:", "2013-05-23"]
	},	
	"activity17":{
		"name": 	["Name:","Keith Kucera"],
		"pass":	    ["Password:", "123"],
		"gender": 	["Gender:", "Male"],
		"weight": 	["Weight:", "160"],
		"muscle": 	["Activity:", "Back"],
		"sets": 	["Number of Sets:", "3"],
		"reps":		["Number of Reps:", "10"],
		"cardio":	["Cardio Today:", false],
		"time":		["Cardio Time:", "0 Minutes"],
		"notes":	["Notes:", ""],
		"date":		["Date:", "2013-05-23"]
	},	
	"activity18":{
		"name": 	["Name:","Chayna Basta"],
		"pass":	    ["Password:", "123"],
		"gender": 	["Gender:", "Female"],
		"weight": 	["Weight:", "280"],
		"muscle": 	["Activity:", "Cardio"],
		"sets": 	["Number of Sets:", "3"],
		"reps":		["Number of Reps:", "10"],
		"cardio":	["Cardio Today:", true],
		"time":		["Cardio Time:", "30 Minutes"],
		"notes":	["Notes:", ""],
		"date":		["Date:", "2013-05-23"]
	},	
	"activity19":{
		"name": 	["Name:","John Michealson"],
		"pass":	    ["Password:", "123"],
		"gender": 	["Gender:", "Male"],
		"weight": 	["Weight:", "145"],
		"muscle": 	["Activity:", "Rest"],
		"sets": 	["Number of Sets:", "0"],
		"reps":		["Number of Reps:", "0"],
		"cardio":	["Cardio Today:", false],
		"time":		["Cardio Time:", "0 Minutes"],
		"notes":	["Notes:", ""],
		"date":		["Date:", "2013-05-28"]
	},	
	"activity20":{
		"name": 	["Name:","Bradley Clark"],
		"pass":	    ["Password:", "123"],
		"gender": 	["Gender:", "Male"],
		"weight": 	["Weight:", "210"],
		"muscle": 	["Activity:", "Rest"],
		"sets": 	["Number of Sets:", "0"],
		"reps":		["Number of Reps:", "0"],
		"cardio":	["Cardio Today:", false],
		"time":		["Cardio Time:", "0 Minutes"],
		"notes":	["Notes:", ""],
		"date":		["Date:", "2013-05-29"]
	}
}